//Routes
export * from '@bn8-navigator/detalle/detalle-routing.module'
export * from '@bn8-navigator/navigator-routing.module'
export * from '@bn8-navigator/general/general-routing.module'
export * from '@bn8-navigator/gestion/gestion-routing.module'
export * from '@bn8-navigator/chat/chat-routing.module'
export * from '@bn8-navigator/notificaciones/notificaciones-routing.module'

//Sub Routes
//General
export * from '@bn8-navigator/general/info/info-routing.module'
export * from '@bn8-navigator/general/estadisticas/estadisticas-routing.module'
export * from '@bn8-navigator/general/bans/bans-routing.module'
export * from '@bn8-navigator/general/preferencias/preferencias-routing.module'
//Gestion
export * from '@bn8-navigator/gestion/promos/promos-routing.module'
export * from '@bn8-navigator/gestion/clubs/clubs-routing.module'
export * from '@bn8-navigator/gestion/planes/planes-routing.module'
export * from '@bn8-navigator/gestion/eventos/eventos-routing.module'
export * from '@bn8-navigator/gestion/entradas/entradas-routing.module'
export * from '@bn8-navigator/gestion/empleados/empleados-routing.module'
//Detalles
export * from '@bn8-detalle/list-requisitos/list-requisitos-routing.module'
export * from '@bn8-detalle/list-propietarios/list-propietarios-routing.module'
export * from '@bn8-detalle/list-publico/list-publico-routing.module'
export * from '@bn8-detalle/list-listas/list-listas-routing.module'
export * from '@bn8-detalle/list-fechas/list-fechas-routing.module'
export * from '@bn8-detalle/list-estadisticas/list-estadisticas-routing.module'
export * from '@bn8-detalle/list-entradas/list-entradas-routing.module'
export * from '@bn8-detalle/list-empleados/list-empleados-routing.module'
export * from '@bn8-detalle/list-clubs/list-clubs-routing.module'
export * from '@bn8-detalle/file-picker/file-picker-routing.module'
export * from '@bn8-detalle/detalle-info-entrada/detalle-info-entrada-routing.module'
export * from '@bn8-detalle/detalle-info-empleado/detalle-info-empleado-routing.module'
export * from '@bn8-detalle/detalle-info-club/detalle-info-club-routing.module'
export * from '@bn8-detalle/detalle-info-promo/detalle-info-promo-routing.module'
export * from '@bn8-detalle/detalle-info-plan/detalle-info-plan-routing.module'
export * from '@bn8-detalle/list-traducciones/list-traducciones-routing.module'
export * from '@bn8-detalle/detalle-info-event/detalle-info-event-routing.module'
export * from '@bn8-detalle/list-tags/list-tags-routing.module'

